framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    php_errors:
        log: true
