security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            provider: main
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin_dashboard
            logout:
                path: admin_logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }