title:
    label: "Titre"
social_networks:
    facebook:
        label: "Lien Facebook"
    twitter:
        label: "Lien Twitter"
    instagram:
        label: "Lien Instagram"
google_analytics:
    gtag:
        label: "Google Analytics GTAG"
aws:
    credentials:
        key:
            label: "Clé AWS"
        secret:
            label: "Secret AWS"
    s3:
        bucket:
            label: "Bucket AWS"
        region:
            label: "Région du Bucket AWS"
