parameters:
    s4blog_dir: "%kernel.project_dir%/s4blog"
    s4blog_media_dir: "%kernel.project_dir%/public/s4b/media"

services:
    s4blog.config.driver:
        class: S4Blog\Core\Config\ConfigDriver
        public: true
        arguments:
            - "%kernel.project_dir%/config/s4blog/config.yaml"

    s4blog.config:
        class: S4Blog\Core\Config\Config
        public: true
        arguments:
            - "@s4blog.config.driver"

    s4blog.app:
        class: S4Blog\Core\BlogApplication
        public: true
        arguments:
            - "@s4blog.config"

    s4blog.config.metadata:
        class: S4Blog\Core\Config\ConfigMetadata
        public: true
        arguments:
            - "@s4blog.config"
            - "%s4blog_dir%/Resources/config/config_metadata.yaml"

    s4blog.config.form:
        class: S4Blog\Core\Config\ConfigForm
        public: true
        arguments:
            - "@s4blog.app"
            - "@form.factory"
            - "@s4blog.config.metadata"

    s4blog.twig.config:
        class: S4Blog\Core\Twig\ConfigTwigExtension
        public: true
        tags: ["twig.extension"]
        arguments:
            - "@s4blog.config"

    s4blog.media.aws_media_driver:
        class: S4Blog\Core\Media\AWSMediaDriver
        public: true
        arguments:
            - "@s4blog.config"

    s4blog.media.filesystem_media_driver:
        class: S4Blog\Core\Media\FilesystemMediaDriver
        public: true
        arguments:
            - "%s4blog_media_dir%"
            - "@twig.extension.httpfoundation"
            - "@assets.packages"

    s4blog.media.media_manager:
        class: S4Blog\Core\Media\MediaManager
        public: true
        arguments:
            - "@s4blog.media.aws_media_driver"

    s4blog.article.manager:
        class: S4Blog\Core\Article\ArticleManager
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"