parameters:
    s4blog_dir: "%kernel.project_dir%/s4blog"
    s4blog_media_dir: "%kernel.project_dir%/public/s4b/media"

services:
    s4blog.config.driver:
        class: S4Blog\Core\Config\ConfigDriver
        public: true
        arguments:
            - "%kernel.project_dir%/config/s4blog/config.yaml"

    s4blog.config:
        class: S4Blog\Core\Config\Config
        public: true
        arguments:
            - "@s4blog.config.driver"

    s4blog.app:
        class: S4Blog\Core\BlogApplication
        public: true
        arguments:
            - "@s4blog.config"

    s4blog.config.metadata:
        class: S4Blog\Core\Config\ConfigMetadata
        public: true
        arguments:
            - "@s4blog.config"
            - "%s4blog_dir%/Resources/config/config_metadata.yaml"

    s4blog.config.form:
        class: S4Blog\Core\Config\ConfigForm
        public: true
        arguments:
            - "@s4blog.app"
            - "@form.factory"
            - "@s4blog.config.metadata"

    s4blog.template.google_analytics_configuration:
        class: S4Blog\Core\GoogleAnalytics\GoogleAnalyticsTemplateConfiguration
        public: true
        tags: ["s4b.template.configuration"]
        arguments:
            - "@twig"

    s4blog.template.facebook_opengraph_configuration:
        class: S4Blog\Core\Facebook\FacebookOpenGraphTemplateConfiguration
        public: true
        tags: ["s4b.template.configuration"]
        arguments:
            - "@twig"

    s4blog.template.twitter_card_configuration:
        class: S4Blog\Core\Twitter\TwitterCardTemplateConfiguration
        public: true
        tags: ["s4b.template.configuration"]
        arguments:
            - "@twig"

    s4blog.template.configurator:
        class: S4Blog\Core\Template\TemplateConfigurator
        public: true

    s4blog.twig.config:
        class: S4Blog\Core\Twig\ConfigTwigExtension
        public: true
        tags: ["twig.extension"]
        arguments:
            - "@s4blog.config"

    s4blog.twig.template_configurator:
        class: S4Blog\Core\Twig\TemplateConfiguratorTwigExtension
        public: true
        tags: ["twig.extension"]
        arguments:
            - "@s4blog.template.configurator"

    s4blog.media.aws_media_driver:
        class: S4Blog\Core\Media\AWSMediaDriver
        public: true
        arguments:
            - "@s4blog.config"

    s4blog.media.filesystem_media_driver:
        class: S4Blog\Core\Media\FilesystemMediaDriver
        public: true
        arguments:
            - "%s4blog_media_dir%"
            - "@twig.extension.httpfoundation"
            - "@assets.packages"

    s4blog.media.media_manager:
        class: S4Blog\Core\Media\MediaManager
        public: true
        arguments:
            - "@s4blog.media.aws_media_driver"

    s4blog.article.manager:
        class: S4Blog\Core\Article\ArticleManager
        public: true
        arguments:
            - "%s4blog.article.entity%"
            - "@doctrine.orm.entity_manager"

    s4blog.newsletter.email_address.manager:
        class: S4Blog\Core\Newsletter\EmailAddressManager
        public: true
        arguments:
            - "%s4blog.newsletter.email_address_entity%"
            - "@doctrine.orm.entity_manager"

    s4blog.google_analytics.client:
        class: S4Blog\Core\GoogleAnalytics\GoogleClient
        public: true
        arguments:
            - "%s4blog.google_analytics.auth_file_path%"
            - "@?debug.stopwatch"

